namespace :temp do

	desc "Extract the resources so they can be imported by the catalog"
	task :extract_resources => :environment do
		raise "This task was designed for one-time use. The FacetCategory and Site tables are no longer a good place to get the resources."
		out = {}
		categories = FacetCategory.all()
		categories.each { |category|
			if category.type == 'FacetValue'
				site = Site.find_by_code(category.value)
				out[category.id] = { :type => 'archive', :parent_id => category.parent_id, :handle => category.value,
					:carousel_include => category.carousel_include,
					:carousel_description => category.carousel_description, :image_id => category.image_id ? category.image.photo.url : nil,
					:url => site.url,
					:friendly_name => site.description, :site_thumbnail => site.thumbnail }
			elsif category.type == nil
				out[category.id] = { :type => 'node', :parent_id => category.parent_id,
					 :carousel_include => category.carousel_include,
					 :carousel_description => category.carousel_description, :image_id => category.image_id ? category.image.photo.url : nil,
					:friendly_name => category.value }
			end
		}

		File.open("#{Rails.root}/tmp/resources.rb", 'w') {|f|
			f.puts "# encoding: UTF-8"
			f.puts "# generated by a rake task in Collex"
			f.puts ""
			f.puts "Archive.delete_all()"
			f.puts ""
			f.puts "archives = ["

			out.each { |key,value|
				value[:carousel_include] = 0 if value[:carousel_include] == nil
				parent = out[value[:parent_id]]
				parent_name = parent ? parent[:friendly_name] : ""
				name = value[:friendly_name] ? value[:friendly_name].gsub('"', '\\"') : ""
				desc = value[:carousel_description] ? value[:carousel_description].gsub('"', '\\"').gsub("\n", '') : ""
				if value[:image_id]
					value[:image_id] = value[:image_id].split('?')[0]
				end

				str = "\t{ "
				str += ":typ => \"#{value[:type]}\","
				str += ":name => \"#{name}\","
				str += ":parent_id => \"#{parent_name}\","
				str += ":carousel_include => \"#{value[:carousel_include]}\",\n"
				str += "\t\t:carousel_description => \"#{desc}\",\n"
				str += "\t\t:image_id => \"#{value[:image_id]}\""
				if value[:type] == 'archive'
					str += ", :handle => \"#{value[:handle]}\", "
					str += ":site_url => \"#{value[:url]}\", "
					str += ":thumbnail => \"#{value[:site_thumbnail]}\""
				end
				f.puts "#{str}\n\t},\n"
			}
			f.puts "]"
			f.puts ""
			f.puts "archives.each { |archive|"
			f.puts "\tdo_delay = false"
			f.puts "\tif archive[:parent_id] == ''\n\t\tarchive[:parent_id] = 0\n\telse\n\t\tparent = Archive.find_by_name(archive[:parent_id])"
			f.puts "\t\tif parent"
			f.puts "\t\t\tarchive[:parent_id] = parent.id"
			f.puts "\t\telse"
			f.puts "\t\t\tdo_delay = true"
			f.puts "\t\t\tarchives.push(archive)"
			f.puts "\t\tend"
			f.puts "\tend"
			f.puts ""
			f.puts "\tif do_delay == false"
			f.puts "\t\timg = archive[:image_id]"
			f.puts "\t\tarchive.delete(:image_id)"
			f.puts "\t\trec = Archive.new(archive)"
			f.puts "\t\tFile.open(\"\#{Rails.root}/../collex/public/\#{img}\") { |photo_file| rec.carousel_image = photo_file } if img.length > 0"
			f.puts "\t\trec.save"
			f.puts "\tend"
			f.puts "}"
			f.puts ""
		}
	end
end
