#!/usr/bin/ruby

##########################################################################
# Copyright 2007 Applied Research in Patacriticism and the University of Virginia
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##########################################################################



if ARGV.empty?
  puts "Usage: benchmarker times 'Person.expensive_way' 'Person.another_expensive_way' ..."
  exit 
end

require File.dirname(__FILE__) + '/../config/environment'
require 'benchmark'
include Benchmark

# Don't include compilation in the benchmark
ARGV[1..-1].each { |expression| eval(expression) }

bm(6) do |x|
  ARGV[1..-1].each_with_index do |expression, idx|
    x.report("##{idx + 1}") { ARGV[0].to_i.times { eval(expression) } }
  end
end 