#!/usr/bin/env ruby

##########################################################################
# Copyright 2007 Applied Research in Patacriticism and the University of Virginia
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##########################################################################


require File.dirname(__FILE__) + '/../config/boot'
require RAILS_ROOT + '/config/environment'

exhibited_resources = ExhibitedResource.find(:all)
exhibited_resources.each do |er|
  er.resource.properties.each do |prop|
    er.properties.create(:name => prop.name, :value => prop.value) unless er.properties.include?(prop)
  end
end
