#!/usr/bin/env ruby

##########################################################################
# Copyright 2007 Applied Research in Patacriticism and the University of Virginia
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##########################################################################


require File.dirname(__FILE__) + '/../config/boot'
require RAILS_ROOT + '/config/environment'

solr = Solr::Connection.new(SOLR_URL)
solr.delete_by_query("type:C")
solr.commit
source = Solr::Importer::SolrSource.new(SOLR_URL,'*:*',nil,:field_list => ['uri'])
uris = []
source.each {|doc| uris << doc['uri']}
puts "Processing #{uris.size} objects..."
i = 0
uris.each do |uri|
  req = Solr::Request::ModifyDocument.new(:uri => uri, :overwrite => {:date_updated => nil, :type => nil})
  solr.send(req)
  i = i + 1
  if i % 1000 == 0
    puts i 
    solr.commit
  end
end
solr.commit
puts "Done."